### ISSUE TITLE
ImportError: No module named PySide

### ISSUE THREAD

**Issue by onur-degerli** [birolkuyumcu/twitterMonitor#1]
Hi,

I have just clone your repo.
When I try to run $ python twitterMonitor.py, I got this error:

Traceback (most recent call last):
  File "twitterMonitor.py", line 15, in <module>
    from PySide import QtCore, QtGui
ImportError: No module named PySide

I use Mac and I tried to install PySide using this instruction:
http://pyside.readthedocs.io/en/latest/building/macosx.html
Even so, it couldn't run.

Do you have any idea?

**Comment by birolkuyumcu** [comment]
hi
issu e not related to code 

probably pyside not installed properly

try Python dist. like anaconda

http://anaconda.org/anaconda/pyside
